/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AssetAssetIdRouteImport } from './routes/asset.$assetId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as LessonLessonIdQuizRouteImport } from './routes/lesson.$lessonId_.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetAssetIdRoute = AssetAssetIdRouteImport.update({
  id: '/asset/$assetId',
  path: '/asset/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdQuizRoute = LessonLessonIdQuizRouteImport.update({
  id: '/lesson/$lessonId_/quiz',
  path: '/lesson/$lessonId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/lesson/$lessonId/quiz': typeof LessonLessonIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/lesson/$lessonId/quiz': typeof LessonLessonIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/lesson/$lessonId_/quiz': typeof LessonLessonIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/league'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/asset/$assetId'
    | '/lesson/$lessonId'
    | '/lesson/$lessonId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/league'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/asset/$assetId'
    | '/lesson/$lessonId'
    | '/lesson/$lessonId/quiz'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/league'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/asset/$assetId'
    | '/lesson/$lessonId'
    | '/lesson/$lessonId_/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LeagueRoute: typeof LeagueRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  AssetAssetIdRoute: typeof AssetAssetIdRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  LessonLessonIdQuizRoute: typeof LessonLessonIdQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$assetId': {
      id: '/asset/$assetId'
      path: '/asset/$assetId'
      fullPath: '/asset/$assetId'
      preLoaderRoute: typeof AssetAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId_/quiz': {
      id: '/lesson/$lessonId_/quiz'
      path: '/lesson/$lessonId/quiz'
      fullPath: '/lesson/$lessonId/quiz'
      preLoaderRoute: typeof LessonLessonIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LeagueRoute: LeagueRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  AssetAssetIdRoute: AssetAssetIdRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  LessonLessonIdQuizRoute: LessonLessonIdQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
